[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/docs"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
numReplicas = 1

[deploy.envVars]
DATABASE_URL = "${{ Postgres-af7H.DATABASE_URL }}"
DATABASE_PUBLIC_URL = "${{ Postgres-af7H.DATABASE_PUBLIC_URL }}"
ALLOWED_ORIGINS = "http://localhost:3000,https://personal-trainer-app-topaz.vercel.app"
PORT = "8080" 